Redirect stderr to stdout to print errors
Inside the systemd environment /dev/stderr is not available.

diff --git a/debian/libexec/update b/debian/libexec/update
--- a/debian/libexec/update
+++ b/debian/libexec/update
@@ -2,7 +2,7 @@
 set -euo pipefail
 
 if [ ! -f "/etc/apt/sources.list.d/fruitnanny.list" ]; then
-    echo "Error: /etc/apt/sources.list.d/fruitnanny.list not found" > /dev/stderr
+    >&2 echo "Error: /etc/apt/sources.list.d/fruitnanny.list not found"
     exit 1
 fi
 
diff --git a/debian/libexec/upgrade b/debian/libexec/upgrade
--- a/debian/libexec/upgrade
+++ b/debian/libexec/upgrade
@@ -2,7 +2,7 @@
 set -euo pipefail
 
 if ! systemctl --all --type service | grep -q "nginx.service"; then
-    echo "Error: service fruitnanny-upgrade.service not found" > /dev/stderr
+    >&2 echo "Error: service fruitnanny-upgrade.service not found" > /dev/stderr
     exit 1
 fi
 
