Use systemd service to fetch updates
Otherwise the update can be triggered multiple times and a restart of
the server could crash the update process.

diff --git a/debian/libexec/update b/debian/libexec/update
--- a/debian/libexec/update
+++ b/debian/libexec/update
@@ -1,12 +1,13 @@
 #!/usr/bin/pkexec /bin/bash
-set -euo pipefail
 
-if [ ! -f "/etc/apt/sources.list.d/fruitnanny.list" ]; then
-    >&2 echo "Error: /etc/apt/sources.list.d/fruitnanny.list not found"
+# Verify if service exists. Otherwise, the "start --wait" call will block
+# indefinitely.
+systemctl status fruitnanny-update.service > /dev/null
+rc=$?
+
+if [ $rc -eq 4 ]; then
+    >&2 echo "Error: service fruitnanny-update.service not found"
     exit 1
 fi
 
-exec /usr/bin/apt update -q \
-    --no-list-cleanup \
-    -o Dir::Etc::sourcelist="sources.list.d/fruitnanny.list" \
-    -o Dir::Etc::sourceparts="-"
+exec systemctl start --wait fruitnanny-update.service
