Use systemd to run upgrade process
Instead of running the upgrade as child process of the fruitnanny-api,
use a systemd one-shot service to execute the upgrade. This gives the
benefit, that the upgrade process is only triggered once but multiple
upgrade processes can wait on the systemd service to finish.
Furthermore, the upgrade process survices an API service shutdown and
restart.

diff --git a/debian/libexec/upgrade b/debian/libexec/upgrade
--- a/debian/libexec/upgrade
+++ b/debian/libexec/upgrade
@@ -1,4 +1,9 @@
 #!/usr/bin/pkexec /bin/bash
 set -euo pipefail
 
-exec /usr/bin/apt install -y --only-upgrade fruitnanny-ui fruitnanny-api rws
+if ! systemctl --all --type service | grep -q "nginx.service"; then
+    echo "Error: service fruitnanny-upgrade.service not found" > /dev/stderr
+    exit 1
+fi
+
+exec systemctl start --wait fruitnanny-upgrade.service
