Fix check for existence of systemd service
Since the service is not enabled, it is not listed by systemd.
Replacing the search in the list by a call to `systemctl status`. The
exit code shows of the service is found or not.

diff --git a/debian/libexec/upgrade b/debian/libexec/upgrade
--- a/debian/libexec/upgrade
+++ b/debian/libexec/upgrade
@@ -1,8 +1,12 @@
 #!/usr/bin/pkexec /bin/bash
-set -euo pipefail
 
-if ! systemctl --all --type service | grep -q "nginx.service"; then
-    >&2 echo "Error: service fruitnanny-upgrade.service not found" > /dev/stderr
+# Verify if service exists. Otherwise, the "start --wait" call will block
+# indefinitely.
+systemctl status fruitnanny-upgrade.service > /dev/null
+rc=$?
+
+if [ $rc -eq 4 ]; then
+    >&2 echo "Error: service fruitnanny-upgrade.service not found"
     exit 1
 fi
 
